<?php

/**
 * @file
 * Provides a simple entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\simple_entity\Entity\SimpleEntity;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function simple_entity_theme() {
  return [
    'simple_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for simple entity templates.
 *
 * Default template: simple-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the simple entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_simple_entity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function simple_entity_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish simple entities.
      $storage = \Drupal::entityTypeManager()->getStorage('simple_entity');
      $simple_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($simple_entity_ids) as $simple_entity) {
        $simple_entity->set('status', FALSE);
        $simple_entity->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize simple entities.
      $storage = \Drupal::entityTypeManager()->getStorage('simple_entity');
      $simple_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($simple_entity_ids) as $simple_entity) {
        $simple_entity->setOwnerId(0);
        $simple_entity->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function simple_entity_user_predelete(UserInterface $account) {
  // Delete simple entities.
  $storage = \Drupal::entityTypeManager()->getStorage('simple_entity');
  $simple_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $simple_entities = $storage->loadMultiple($simple_entity_ids);
  $storage->delete($simple_entities);
}
