_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 1b918d53-78f1-4572-84b5-c343798345bf
name: 'Drupal 9'
mail: admin@example.com
slogan: 'Content management system'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
