name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
      - name: copy env
        run: cp .env.dist .env      
      - name: Build
        run: make up
      - name: mkdir_web
        run: mkdir web
      # - name: Pre-Install
      #   run: docker-compose exec -T --user=root php bash -c 'chown -R www-data:vitalii /var/www'
       
      - name: create composer files
        run: cp composer.json composer.lock web
      - name: debug
        run: pwd && ls -la && whomai && docker-compose exec -T php bash -c 'pwd && ls -la && whomai' && 
      - name: composer_install
        run: make composer_install
      - name: Copy settings
        run: cp settings.php web/sites/default/
      - name: site_install
        run: make site_install
      - name: Test
        run: make test