name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
      - name: copy env
        run: cp .env.dist .env      
      - name: Make up
        run: make up
      - name: Pre-Install
        run: docker-compose exec -T --user=root php bash -c 'chown -R vitalii /var/www' && useradd -r -g systemd-coredump vitalii
      - name: mkdir_web
        run: mkdir web    
       
      - name: create composer files
        run: cp composer.json composer.lock web
      - name: debug
        run: pwd && ls -la && whoami && id  && id systemd-coredump && docker-compose exec -T php bash -c 'pwd && ls -la && whoami && id'
      - name: composer_install
        run: make composer_install
      - name: Copy settings
        run: cp settings.php web/sites/default/ 
        # && mkdir web/sites/www/ && cp settings.php web/sites/www/

      # - name: list
      #   run: make list

      - name: site_install
        run: make site_install
      - name: Test
        run: make test