name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
      - name: copy env
        run: cp .env.dist .env
      # - name: help
      #   run: make help
      - name: Build
        run: make up
      - name: Pre-Install
        run: docker-compose exec -T --user=root php bash -c 'chown -R www-data:www-data /var/www'
      - name: mkdir_web
        run: mkdir web
      - name: create composer files
        run: cp composer.json composer.lock web
      - name: composer_install
        run: make composer_install
      - name: Copy settings
        run: cp settings.php web/sites/default/
      - name: site_install
        run: make site_install
      - name: Test
        run: make test